# This is a basic workflow to help you get started with Actions

name: Docker Laravel + Nextjs build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs docker-compose build command
      - name: docker build
        run:  docker-compose up -d --build
      # Install composer dependancies
      - name: Install Composer Dependencies
        run: docker-compose run --rm composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      # Install composer dependancies
      - name: Update Composer Dependencies
        run: docker-compose run --rm composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      # Create storage link between public and storage folders
      - name: Storage Link
        run: docker-compose run --rm artisan storage:link
      # Setup permissions
      - name: Directory Permissions
        run: docker-compose run --rm php chmod -R 777 storage bootstrap/cache
      # Install npm dependencies
      - name: Install npm dependencies
        run: docker-compose run --rm npm ci
      # # Install tailwind dependencies
      # - name: Install tailwind dependencies
      #   run: docker-compose run --rm npm install -D tailwindcss@latest postcss@latest autoprefixer@latest
      #Compile Mix Assets
      - name: Run Mix
        run: docker-compose run --rm npm run prod
